/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONPDM_H_RPCGEN
#define _GESTIONPDM_H_RPCGEN

#include <rpc/rpc.h>
#include "gestionPdM2.h"


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXDAT 12

struct datos_pdm {
	int codigo;
	char nombrePrograma[MAXNOM];
	char nombreCoordinador[MAXNOM];
	char usuario[MAXDAT];
	char clave[MAXDAT];
};
typedef struct datos_pdm datos_pdm;

struct datos_sesion {
	int codigo;
	char usuario[MAXDAT];
	char clave[MAXDAT];
};
typedef struct datos_sesion datos_sesion;

struct matrizDocente_pdm {
	int codigo;
	char fuente[MAXNOM];
	char tipoHallazgo[MAXNOM];
	char factor[MAXNOM];
	char descripcion[MAXNOM];
	char proyecto[MAXNOM];
	char responsable[MAXNOM];
};
typedef struct matrizDocente_pdm matrizDocente_pdm;

struct matrizCGC_pdm {
	int codigo;
	int porcentaje;
	char evidencia[MAXNOM];
	char fechaInicio[MAXNOM];
	char fechaFinal[MAXNOM];
};
typedef struct matrizCGC_pdm matrizCGC_pdm;

#define gestion_pdm 0x20000001
#define gestion_pdm_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarPdM 1
extern  bool_t * registrarpdm_1(datos_pdm *, CLIENT *);
extern  bool_t * registrarpdm_1_svc(datos_pdm *, struct svc_req *);
#define consultarPdM 2
extern  datos_pdm * consultarpdm_1(int *, CLIENT *);
extern  datos_pdm * consultarpdm_1_svc(int *, struct svc_req *);
#define abrirSesion 3
extern  datos_pdm * abrirsesion_1(datos_sesion *, CLIENT *);
extern  datos_pdm * abrirsesion_1_svc(datos_sesion *, struct svc_req *);
#define registrarDocentePdM 4
extern  bool_t * registrardocentepdm_1(matrizDocente_pdm *, CLIENT *);
extern  bool_t * registrardocentepdm_1_svc(matrizDocente_pdm *, struct svc_req *);
#define registrarCGCPdM 5
extern  bool_t * registrarcgcpdm_1(matrizCGC_pdm *, CLIENT *);
extern  bool_t * registrarcgcpdm_1_svc(matrizCGC_pdm *, struct svc_req *);
extern int gestion_pdm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarPdM 1
extern  bool_t * registrarpdm_1();
extern  bool_t * registrarpdm_1_svc();
#define consultarPdM 2
extern  datos_pdm * consultarpdm_1();
extern  datos_pdm * consultarpdm_1_svc();
#define abrirSesion 3
extern  datos_pdm * abrirsesion_1();
extern  datos_pdm * abrirsesion_1_svc();
#define registrarDocentePdM 4
extern  bool_t * registrardocentepdm_1();
extern  bool_t * registrardocentepdm_1_svc();
#define registrarCGCPdM 5
extern  bool_t * registrarcgcpdm_1();
extern  bool_t * registrarcgcpdm_1_svc();
extern int gestion_pdm_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_pdm (XDR *, datos_pdm*);
extern  bool_t xdr_datos_sesion (XDR *, datos_sesion*);
extern  bool_t xdr_matrizDocente_pdm (XDR *, matrizDocente_pdm*);
extern  bool_t xdr_matrizCGC_pdm (XDR *, matrizCGC_pdm*);

#else /* K&R C */
extern bool_t xdr_datos_pdm ();
extern bool_t xdr_datos_sesion ();
extern bool_t xdr_matrizDocente_pdm ();
extern bool_t xdr_matrizCGC_pdm ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONPDM_H_RPCGEN */
