/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "monitorPdM.h"
#include "gestionPdM.h"
#include "gestionPdM2.h"

datos_pdm vectorPdM[5];
matrizDocente_pdm vectorDocentesPdM[5];
matrizCGC_pdm vectorCGC[5];
int posPdM=0;
int posPdMDoc = 0;

bool_t *
registrarpdm_1_svc(datos_pdm *argp, struct svc_req *rqstp)
{
	static bool_t  result;


printf("\n Invocando a registrar anteproyecto");
if(posPdM < 5)
   { 
     vectorPdM[posPdM]=*argp;
     posPdM++;
     printf("\n PdM registrado exitósamente");
     result = TRUE;
   }
 else
   {
     printf("\n PdM NO registrado, se alcanzó la cantidad máxima de PdM a registrar");
     result = FALSE;
   }
	return &result;
}

datos_pdm *
consultarpdm_1_svc(int *argp, struct svc_req *rqstp)
{
	static datos_pdm  result;
printf("\n Invocando a consultar Plan de Mejoramiento");
   int i, bandera;
    bandera = 0;
    for(i = 0; i < 5; i++)
    {
  
      if(vectorPdM[i].codigo == *argp)
     {
        result = vectorPdM[i];
        bandera = 1;
       break;
      }
   }
   if(bandera == 0)
   {
     printf("*PdM NO encontrado*", *argp);
     result.codigo = -1;
   }

	return &result;

}

datos_pdm *
abrirsesion_1_svc(datos_sesion *argp, struct svc_req *rqstp)
{
	static datos_pdm  result;

	CLIENT *clnt;
	void  *result_1;
	int  enviarnotificacion_1_arg;

#ifndef	DEBUG
char *host="localhost";
	clnt = clnt_create (host, monitor_pdm, monitor_pdm_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
printf("\n Consultando credenciales...\n");
	for(int i = 0; i<5; i++){
	if(argp->codigo == vectorPdM[i].codigo && strcmp(argp->usuario, vectorPdM[i].usuario) == 0 && strcmp(argp->clave,vectorPdM[i].clave) == 0){
		
		
		result = vectorPdM[i];
		enviarnotificacion_1_arg = argp->codigo;	
		printf("Sesion iniciada correctamente \n");
		result_1 = enviarnotificacion_1(&enviarnotificacion_1_arg, clnt);
		printf("resultado: %d",enviarnotificacion_1_arg);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

}

}
	return &result;
}

bool_t *
registrardocentepdm_1_svc(matrizDocente_pdm *argp, struct svc_req *rqstp)
{
printf("\n Invocando a llenar matriz mejora anteproyecto");
CLIENT *clnt;	
static bool_t  result;
static bool_t  result_2;
#ifndef	DEBUG
char *host="localhost";
	clnt = clnt_create (host, monitor_pdm, monitor_pdm_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
printf("\n Invocando a llenar matriz mejora anteproyecto");
//if(strcmp(vectorPdM[posPdM].nombreCoordinador, "Coordinador") == 0) { //si no funciona este fue el cambio perrito
for(int i = 0; i<5; i++){
	if(argp->codigo == vectorPdM[i].codigo)
    {
	vectorDocentesPdM[i]=*argp;
	printf("Codigo: %d\n",(argp->codigo));
	printf("Nombre: %s\n",(argp->fuente));
	printf("proyecto: %s\n",(argp->proyecto));
	printf("Responsable: %s\n",(argp->responsable));
	printf("Descripcion: %s\n",(argp->descripcion));
    printf("\n Matriz de PdM registrado exitósamente");
	 //result_2 = *guardarpdm_1(argp,clnt);
	 result_2 = *guardarpdm_1(argp, clnt);
     result = TRUE;

   }
 else
   {
     result = FALSE;
   }
}
	return &result;
}	
//}

bool_t *
registrarcgcpdm_1_svc(matrizCGC_pdm *argp, struct svc_req *rqstp)
{
CLIENT *clnt;	
static bool_t  result;
static bool_t  result_2;
#ifndef	DEBUG
char *host="localhost";
	clnt = clnt_create (host, monitor_pdm, monitor_pdm_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
printf("\n Invocando a llenar matriz mejora anteproyecto como administrativo");
printf("Codigo: %d\n",(argp->codigo));

//if(strcmp(vectorPdM[posPdM].nombreCoordinador, "Coordinador") == 0) { //si no funciona este fue el cambio perrito
for(int i = 0; i<5; i++){
	if(argp->codigo == vectorPdM[i].codigo)
   { 
     vectorCGC[i]=*argp;
     posPdM++;
     printf("\n Matriz de PdM registrado exitósamente");
	 result_2 = *guardarpdms_1(argp,clnt);
	 printf("\n Matriz de PdM registrado exitósamente");
     result = TRUE;

   }
 else
   {
     result = FALSE;
   }
}
	return &result;
}
