/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONPDM2_H_RPCGEN
#define _GESTIONPDM2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define gestion2_pdm 0x30000001
#define gestion2_pdm_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion2 1
extern  void * enviarnotificacion2_1(int *, CLIENT *);
extern  void * enviarnotificacion2_1_svc(int *, struct svc_req *);
extern int gestion2_pdm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion2 1
extern  void * enviarnotificacion2_1();
extern  void * enviarnotificacion2_1_svc();
extern int gestion2_pdm_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONPDM2_H_RPCGEN */
