/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionPdM2.h"
#include "gestionPdM.h"


datos_pdm vectorPdM[5];
matrizDocente_pdm vectorDocentesPdM[5];

matrizDocente_pdm  registrardocentepdm_1_arg;
	
char *cadenas[4] = {"Autoevaluacion", "Evaluacion_de_pares", "Auditoria_Externa", "Auditoria_interna"};
	char *factores[4] = {"Proyecto_Institucional", "Estudiantes", "Profesores", "Egresados"};
	char *roles[4] = {"Coordinador", "auditorInterno","auditorOCI"};
int posPdM=0;
int posPdMDoc = 0;

void *
enviarnotificacion2_1_svc(int *argp, struct svc_req *rqstp)
{
     
    bool_t  *result_4;
    datos_pdm  *result_2;
	CLIENT *clnt;	

char *host="localhost";
#ifndef	DEBUG
	clnt = clnt_create (host, gestion_pdm, gestion_pdm_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	static char * result;
	   printf("================ Ha accedido como Coordinador ==================\n");

    int codigo;
    printf("Ingrese nombre codigo del proyecto: \n");
    scanf("%d", &codigo);
	
    registrardocentepdm_1_arg.codigo = codigo;

    int opcion2;
    printf("\n================ Opciones para la fuente ==================");
    printf("\n 0. %s", cadenas[0]);
    printf("\n 1. %s", cadenas[1]);
    printf("\n 2. %s", cadenas[2]);
    printf("\n 3. %s", cadenas[3]);
    scanf("%d", &opcion2);
    strcpy(registrardocentepdm_1_arg.fuente, cadenas[opcion2]);	

    int opcion3;
    printf("\n================ Opciones para los Factores ==================");
    printf("\n 0. %s", factores[0]);
    printf("\n 1. %s", factores[1]);
    printf("\n 2. %s", factores[2]);
    printf("\n 3. %s", factores[3]);
    scanf("%d", &opcion3);
    strcpy(registrardocentepdm_1_arg.factor, factores[opcion3]);	

    printf("Escriba su descripcion: \n");
    fgets(registrardocentepdm_1_arg.descripcion, sizeof(registrardocentepdm_1_arg.descripcion), stdin);	

    printf("Escriba su proyecto para superar accion de mejora: \n");
    scanf("%s", registrardocentepdm_1_arg.proyecto);

    printf("Ingrese nombre responsable del proyecto: \n");
    scanf("%s", registrardocentepdm_1_arg.responsable);
    //result_4 = registrardocentepdm_1(&registrardocentepdm_1_arg, clnt);
    result_2 = consultarpdm_1(argp, clnt);
    if ((*result_2).codigo == -1)
			{
				printf("\nPdM NO encontrado");
			}
			else
			{
				printf("\nCodigo del PdM: %d", (*result_2).codigo);
				printf("\nNombre del programa: %s", (*result_2).nombrePrograma);
				printf("\nUsuario: %s", (*result_2).usuario);
				printf("\n Clave: %s", (*result_2).clave);
			}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
 // Aquí es donde falta una llave de cierr
	/*
	 * insert server code here
	 */

	return (void *) &result;
}
