/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionPdM.h"
#include "gestionPdM2.h"


void
gestion_pdm_1(char *host)
{
	CLIENT *clnt;
	CLIENT *clnt2;
	bool_t  *result_1;
	datos_pdm  registrarpdm_1_arg;
	datos_pdm  *result_2;
	int  consultarpdm_1_arg;
	datos_pdm  *result_3;
	datos_sesion  abrirsesion_1_arg;
	bool_t  *result_4;
	matrizDocente_pdm  registrardocentepdm_1_arg;
	bool_t  *result_5;
	matrizCGC_pdm  registrarcgcpdm_1_arg;
	void *result7;
	char *cadenas[4] = {"Autoevaluacion", "Evaluacion_de_pares", "Auditoria_Externa", "Auditoria_interna"};
	char *factores[4] = {"Proyecto_Institucional", "Estudiantes", "Profesores", "Egresados"};
	char *roles[4] = {"Coordinador", "auditorInterno","auditorOCI"};
	
#ifndef	DEBUG

	clnt = clnt_create (host, gestion_pdm, gestion_pdm_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

int opcion;
	do
	{
		printf("\n================ Menu ==================");
		printf("\n 1. Registrar PdM ");
		printf("\n 2. Consultar PdM ");
		printf("\n 3. Iniciar sesion ");
		printf("\n 4. Registrar Como Docente ");
		printf("\n 5. Registrar Como CGC ");
		printf("\n 6. Salir ");
		printf("\n=======================================");
		printf("\n Digite opcion: ");
		scanf("%d", &opcion);
		switch (opcion)
		{
		case 1:
			printf("Digite el codigo: ");
			scanf("%d", &registrarpdm_1_arg.codigo);
			printf("Digite el nombre Del Programa: ");
			scanf("%s", registrarpdm_1_arg.nombrePrograma);
			int opcionN1;
				printf("\n================ Opciones para los Factores ==================");
				printf("\n 0. %s", roles[0]);
				printf("\n 1. %s", roles[1]);
				printf("\n 2. %s", roles[2]);
				scanf("%d", &opcionN1);
			strcpy(registrarpdm_1_arg.nombreCoordinador, roles[opcionN1]);	
			printf("Digite el nombre Usuario: ");
			scanf("%s", registrarpdm_1_arg.usuario);
			printf("Digite la clave: ");
			scanf("%s", registrarpdm_1_arg.clave);
			result_1 = registrarpdm_1(&registrarpdm_1_arg, clnt);
			if (result_1 == (bool_t *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else if (*result_1 == TRUE)
			{
				printf("PdM registrado exitosamente\n");
			}
			else
			{
				printf("\n Pdm NO registrado, se alcanzó l cantidad máxima de PdM a registrar**");
			}
			break;

		case 2:
			printf("\n Consultar documento PdM");
			//consultarpdm_1_arg=(char*)malloc(sizeof(char)*20);
			printf("\nDigite el Codigo del PdM:");
			scanf("%d", &consultarpdm_1_arg);
			result_2 = consultarpdm_1(&consultarpdm_1_arg, clnt);
			if ((*result_2).codigo == -1)
			{
				printf("\nPdM NO encontrado");
			}
			else
			{
				printf("\nCodigo del PdM: %d", (*result_2).codigo);
				printf("\nNombre del programa: %s", (*result_2).nombrePrograma);
				printf("\nUsuario: %s", (*result_2).usuario);
				printf("\n Clave: %s", (*result_2).clave);
			}
			break;

		case 3:
			printf(" Abrir Sesion\n");
			printf("Digite el codigo: \n");
			scanf("%d", &abrirsesion_1_arg.codigo);
			printf("Digite el nombre Usuario: \n");
			scanf("%s", abrirsesion_1_arg.usuario);
			printf("Digite la clave: \n");
			scanf("%s", abrirsesion_1_arg.clave);
			result_3 = abrirsesion_1(&abrirsesion_1_arg, clnt);
			if ((*result_3).codigo == -1)
			{
				printf("\n Usuario NO encontrado");
			}else{
			int numero = 42;
			int *punteroNumero = &numero;
				if(strcmp((*result_3).nombreCoordinador,"Coordinador") == 0 ){
					#ifndef	DEBUG
					clnt2 = clnt_create (host, gestion2_pdm, gestion2_pdm_version, "udp");
					if (clnt2 == NULL) {
						clnt_pcreateerror (host);
						exit (1);
					}
				#endif	/* DEBUG */

					result7 = enviarnotificacion2_1((&abrirsesion_1_arg.codigo),clnt2);					
				}else{
				
				system("clear");
				int codigo;
									
				printf("Ingrese nombre codigo del proyecto: \n");
				scanf("%d", &codigo);
				registrarcgcpdm_1_arg.codigo = codigo;
				int opcion;
					do {
						
						printf("------- MENU -------\n");
						printf("1. Porcentaje de avance.\n");
						printf("2. Evidencias.\n");
						printf("3. Fecha de inicio.\n");
						printf("4. Fecha final.\n");
						printf("0. Salir.\n");
						printf("Ingrese su opcion: ");
						scanf("%d", &opcion);
						switch (opcion) {
							case 1:
								printf("Ha seleccionado la opcion 1: Porcentaje de avance.\n");
								int porcentaje;	
								printf("Ingrese nombre porcentaje de avance del proyecto: \n");
								scanf("%d", &porcentaje);
								registrarcgcpdm_1_arg.porcentaje = porcentaje;
								result_5 = registrarcgcpdm_1(&registrarcgcpdm_1_arg, clnt);
								break;
							case 2:
								printf("Ha seleccionado la opcion 2: Evidencias.\n");
								printf("Ingrese la evidencia del proyecto: \n");
								scanf("%s", registrarcgcpdm_1_arg.evidencia);
								result_5 = registrarcgcpdm_1(&registrarcgcpdm_1_arg, clnt);
								//printf("aaa: %s",registrarcgcpdm_1_arg.evidencia);
								break;
							case 3:
								printf("Ha seleccionado la opcion 3: Fecha de inicio.\n");

								printf("Ingrese la fecha inicio del proyecto: \n");
								scanf("%s", registrarcgcpdm_1_arg.fechaInicio);
								result_5 = registrarcgcpdm_1(&registrarcgcpdm_1_arg, clnt);
								break;
							case 4:
								printf("Ha seleccionado la opcion 4: Fecha final.\n");

								printf("Ingrese la fecha fin del proyecto: \n");
								scanf("%s", registrarcgcpdm_1_arg.fechaFinal);
								result_5 = registrarcgcpdm_1(&registrarcgcpdm_1_arg, clnt);
								break;
							case 0:
								printf("Ha seleccionado la opcion 0: Salir.\n");
								break;
							default:
								printf("Opcion invalida. Por favor, intente de nuevo.\n");
								break;
						}
							} while (opcion != 0);

									
						}
					}	
			break;
		case 4:
			
			
			break;	

		}
	} while (opcion < 7);	
	#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
#ifndef	DEBUG
	clnt_destroy (clnt2);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_pdm_1 (host);
exit (0);
}
