/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MONITORPDM_H_RPCGEN
#define _MONITORPDM_H_RPCGEN

#include <rpc/rpc.h>
#include "gestionPdM.h"


#ifdef __cplusplus
extern "C" {
#endif


#define monitor_pdm 0x30000001
#define monitor_pdm_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion 1
extern  void * enviarnotificacion_1(int *, CLIENT *);
extern  void * enviarnotificacion_1_svc(int *, struct svc_req *);
#define guardarPdM 2
extern  bool_t * guardarpdm_1(matrizDocente_pdm *, CLIENT *);
extern  bool_t * guardarpdm_1_svc(matrizDocente_pdm *, struct svc_req *);
#define guardarPdMS 3
extern  bool_t * guardarpdms_1(matrizCGC_pdm *, CLIENT *);
extern  bool_t * guardarpdms_1_svc(matrizCGC_pdm *, struct svc_req *);
extern int monitor_pdm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion 1
extern  void * enviarnotificacion_1();
extern  void * enviarnotificacion_1_svc();
#define guardarPdM 2
extern  bool_t * guardarpdm_1();
extern  bool_t * guardarpdm_1_svc();
#define guardarPdMS 3
extern  bool_t * guardarpdms_1();
extern  bool_t * guardarpdms_1_svc();
extern int monitor_pdm_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MONITORPDM_H_RPCGEN */
