/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 *matrizPdM-nnnn.txt*/
#include <ctype.h>
#include<stdio.h>
#include "gestionPdM.h"
#include "monitorPdM.h"

void *
enviarnotificacion_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	printf("Desde enviarnotificacion()...\n");
	printf("** PdM con Codigo: %d esta autorizado para ingresar al sistema**", *argp);
	printf("Saliendo de enviarnotificacion()...\n\n");
	//printf("** PdM con Codigo: %d esta autorizado para ingresar al sistema**", *argp);
	return (void *) &result;
}
bool_t *
guardarpdm_1_svc(matrizDocente_pdm *argp, struct svc_req *rqstp)
{
	static bool_t  result = TRUE;
	printf("Guardando_Informacion docente()...\n");
	char filename[50];
	sprintf(filename, "matrizPdM-%d.txt", *(&argp->codigo));
	FILE *archivo = fopen(filename, "a+");

	/*FILE *archivo = fopen(filename, "wb"); */
	if (archivo == NULL) {
		printf("Error al abrir el archivo\n");
		result = FALSE;
		return &result;
	}

	printf("Codigo: %d\n", *(&argp->codigo));
	printf("Nombre: %s\n", *(&argp->fuente));
	printf("Periodo: %s\n", *(&argp->responsable));
	

	//size_t elementos_escritos = fwrite(argp, sizeof(struct matrizDocente_pdm), 1, archivo);
	/*size_t elementos_escritos = fwrite(argp, sizeof(struct matrizDocente_pdm), 1, archivo);
	if (elementos_escritos < 1) {
	    printf("Error al escribir en el archivo\n");
	    result = FALSE;
	}*/
	fprintf(archivo, "%d\n", *(&argp->codigo));
	fprintf(archivo, "%s\n", *(&argp->fuente));
	fprintf(archivo, "%s\n", *(&argp->tipoHallazgo));
	fprintf(archivo, "%s\n", *(&argp->factor));
	fprintf(archivo, "%s\n", *(&argp->descripcion));
	fprintf(archivo, "%s\n", *(&argp->proyecto));
	fprintf(archivo, "%s\n", *(&argp->responsable));
	fclose(archivo);
	archivo = fopen(filename, "rb");
	printf("\nContenido del archivo:\n");

	fclose(archivo);
	return &result;
}

bool_t *
guardarpdms_1_svc(matrizCGC_pdm *argp, struct svc_req *rqstp){
	static bool_t  result = TRUE;
	printf("Guardando_Informacion docente()...\n");
	char filename[50];
	sprintf(filename, "matrizPdM-%d.txt", *(&argp->codigo));
	FILE *archivo = fopen(filename, "a+");
	if (archivo == NULL) {
		printf("Error al abrir el archivo\n");
		result = FALSE;
		return &result;
	}

	fprintf(archivo, "%d\n", *(&argp->porcentaje));
	fprintf(archivo, "%s\n", *(&argp->evidencia));
	fprintf(archivo, "%s\n", *(&argp->fechaInicio));
	fprintf(archivo, "%s\n", *(&argp->fechaFinal));

	fclose(archivo);

return &result;
}
